# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
