# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20160319_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='ships', to=settings.AUTH_USER_MODEL),
        ),
    ]
